# Update all the sections by editing the data.yml file inside _data folder.

# Site Settings

# SEO plugin
title: Fadel Nouraldine
author: Fadel Nouraldine
tagline: Photographer/Football Coach # Short description for jekyll-seo-tag
description: Photographer, football player # Longer description for jekyll-seo-tag

url: "https://fadelnouraldine.github.io"
baseurl: "" # change it according to your repository name

twitter:
  username: stevedoe123
  card: summary

social:
  links:
    - https://www.facebook.com/fadel.nouraldine.5
    - https://github.com/Fadelnouraldine
    - https://www.instagram.com/fadel_nrd/

google_site_verification: # Put your google verification tag here

# End SEO

# Style will be applied only after restarting the build or serve. Just choose one of the options.
theme_skin: gray # gray blue turquoise green berry red

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
compress-site: yes

encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
